package kse.edu.misuratauniversityguide;

public enum Faculties {
    FACULTY_OF_LAW,
    FACULTY_OF_ARTS,
    FACULTY_OF_SCIENCE,
    FACULTY_OF_NURSING,
    FACULTY_OF_MEDICINE,
    FACULTY_OF_PHARMACY,
    FACULTY_OF_ECONOMICS,
    FACULTY_OF_EDUCATION,
    FACULTY_OF_ENGINEERING,
    FACULTY_OF_AGRICULTURE,
    FACULTY_OF_ARTS_AND_MEDIA,
    FACULTY_OF_ISLAMIC_STUDIES,
    FACULTY_OF_PHYSICAL_EDUCATION,
    FACULTY_OF_INFORMATION_TECHNOLOGY,
    FACULTY_OF_DENTISTRY_AND_ORAL_SURGERY,
}
